//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPHONECRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int PhoneId { get; set; }
        public string Model { get; set; }
        public string Company { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
